# Generated by Django 4.2.7 on 2023-11-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mebels", "0002_brand_is_album"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="is_album",
        ),
        migrations.AddField(
            model_name="product",
            name="is_album",
            field=models.BooleanField(
                default=True,
                help_text="Если изображения на странице должны быть показаны как албьомные фото, то отметьте галочкой",
                verbose_name="Альбомные изображения?",
            ),
        ),
    ]
