# Generated by Django 4.2.7 on 2023-11-10 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mebels", "0003_remove_brand_is_album_product_is_album"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productshots",
            name="arkon_url",
        ),
    ]
