# Generated by Django 4.2.7 on 2023-12-07 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mebels", "0007_brand_address_brand_email_brand_email_support_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="brend",
            new_name="brand",
        ),
    ]
