# Generated by Django 4.2.7 on 2023-12-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядковый номер"),
        ),
    ]
