# Generated by Django 4.2.7 on 2023-12-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0002_category_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название таблицы")),
                ("is_show", models.BooleanField(default=True, verbose_name="Показать?")),
            ],
            options={
                "verbose_name": "Таблица",
                "verbose_name_plural": "Таблицы",
            },
        ),
    ]
