# Generated by Django 4.2.7 on 2023-11-06 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт ", "verbose_name_plural": "Продукты "},
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="stones.category",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
