# Generated by Django 4.2.7 on 2023-11-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0002_alter_product_options_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.ImageField(upload_to="stones/brand", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(upload_to="stones/brand", verbose_name="Логотип"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(upload_to="stones/categories", verbose_name="Изображение"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="stones/products", verbose_name="Изображение"),
        ),
    ]
