# Generated by Django 4.2.7 on 2023-11-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0003_alter_brand_image_alter_brand_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="logo_light",
            field=models.ImageField(default=1, upload_to="stones/brand", verbose_name="Логотип для светлой версии"),
            preserve_default=False,
        ),
    ]
