# Generated by Django 4.2.7 on 2023-12-14 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0007_alter_category_options_brand_address_brand_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="brand",
            name="hide",
            field=models.BooleanField(default=False, verbose_name="Скрыть?"),
        ),
        migrations.AddField(
            model_name="brand",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="hide",
            field=models.BooleanField(default=False, verbose_name="Скрыть?"),
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="hide",
            field=models.BooleanField(default=False, verbose_name="Скрыть?"),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                blank=True, null=True, upload_to="stones/products", verbose_name="Изображение на главной 2"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(
                blank=True, null=True, upload_to="stones/products", verbose_name="Изображение на главной 3"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_album",
            field=models.BooleanField(
                default=True,
                help_text="Если изображения на главной странице должны быть показаны как албьомные фото, то отметьте галочкой",
                verbose_name="Альбомные изображения?",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ProductShots",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="stones/product_shots", verbose_name="Изображение")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shots",
                        to="stones.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение продукта ",
                "verbose_name_plural": "Изображения продукта ",
            },
        ),
    ]
