# Generated by Django 4.2.7 on 2023-12-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0008_brand_created_at_brand_hide_brand_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Если продукт не имеет модели, вы можете указать бренд",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="stones.brand",
                verbose_name="Бренд",
            ),
        ),
    ]
