# Generated by Django 4.2.7 on 2023-12-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("stones", "0009_product_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hide", models.BooleanField(default=False, verbose_name="Скрыть?")),
                (
                    "arkon_file",
                    models.FileField(
                        blank=True,
                        default=None,
                        help_text="Укажите файл AR, если в текущей странице нужно отображать AR",
                        null=True,
                        upload_to="",
                        verbose_name="Файл AR",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("image", models.ImageField(upload_to="stones/categories", verbose_name="Изображение")),
            ],
            options={
                "verbose_name": "Модель ",
                "verbose_name_plural": "Модели ",
            },
        ),
        migrations.RemoveField(
            model_name="product",
            name="arkon_url",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image3",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_album",
        ),
        migrations.AddField(
            model_name="brand",
            name="arkon_file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Укажите файл AR, если в текущей странице нужно отображать AR",
                null=True,
                upload_to="",
                verbose_name="Файл AR",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="arkon_file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Укажите файл AR, если в текущей странице нужно отображать AR",
                null=True,
                upload_to="",
                verbose_name="Файл AR",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="categories.category",
                verbose_name="Модель",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="categories",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="stones.brand",
                verbose_name="Бренд",
            ),
        ),
    ]
