# Generated by Django 4.2.7 on 2023-12-14 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("stones", "0010_categories_remove_product_arkon_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="slogan",
            field=models.CharField(default=1, max_length=100, verbose_name="Слоган"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brands",
                to="categories.category",
                verbose_name="Категория",
            ),
        ),
    ]
