# Generated by Django 4.2.7 on 2023-12-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0011_brand_slogan_alter_brand_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="stones.categories",
                verbose_name="Модель",
            ),
        ),
    ]
