# Generated by Django 4.2.7 on 2023-12-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0013_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="icon",
            field=models.ImageField(default="qwe.jpg", upload_to="brands/icons", verbose_name="Иконка в поиске"),
            preserve_default=False,
        ),
    ]
