# Generated by Django 4.2.7 on 2023-12-15 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0014_brand_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandSocials",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("link", models.URLField(verbose_name="Ссылка")),
                (
                    "type",
                    models.CharField(
                        choices=[("fb", "fb"), ("tg", "tg"), ("ig", "ig"), ("tw", "tw"), ("yt", "yt")],
                        default="fb",
                        max_length=2,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="socials", to="stones.brand"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ссылка соц сети",
                "verbose_name_plural": "Ссылки соц сетей",
            },
        ),
    ]
