# Generated by Django 4.2.7 on 2023-12-16 03:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0015_brandsocials"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="country",
            field=django_countries.fields.CountryField(default="UZ", max_length=2),
        ),
        migrations.AlterField(
            model_name="brandsocials",
            name="type",
            field=models.CharField(
                choices=[
                    ("fb", "Facebook"),
                    ("tg", "Telegram"),
                    ("ig", "Instagram"),
                    ("tw", "Twitter"),
                    ("yt", "Youtube"),
                ],
                default="fb",
                max_length=2,
            ),
        ),
    ]
