# Generated by Django 4.2.7 on 2023-12-16 04:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0016_brand_country_alter_brandsocials_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
