# Generated by Django 4.2.7 on 2023-12-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0017_alter_brand_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandsocials",
            name="type",
            field=models.CharField(
                choices=[
                    ("fb", "Facebook"),
                    ("tg", "Telegram"),
                    ("ig", "Instagram"),
                    ("tw", "Twitter"),
                    ("yt", "Youtube"),
                    ("wa", "Whatsapp"),
                ],
                default="fb",
                max_length=2,
            ),
        ),
    ]
