# Generated by Django 4.2.7 on 2023-12-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0018_alter_brandsocials_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandLocations",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("long", models.FloatField(verbose_name="Долгота")),
                ("lat", models.FloatField(verbose_name="Широта")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="locations", to="stones.brand"
                    ),
                ),
            ],
            options={
                "verbose_name": "Локация бренда",
                "verbose_name_plural": "Локации бренда",
            },
        ),
    ]
