# Generated by Django 4.2.7 on 2023-12-21 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0019_brandlocations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brandlocations",
            name="lat",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="brandlocations",
            name="long",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Долгота",
            ),
        ),
    ]
