# Generated by Django 4.2.7 on 2023-12-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0020_alter_brandlocations_lat_alter_brandlocations_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="email_support",
            field=models.CharField(default="example.com", max_length=100, verbose_name="Официальный сайт"),
        ),
    ]
