# Generated by Django 4.2.7 on 2023-12-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0021_alter_brand_email_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="order",
            field=models.IntegerField(default=0, verbose_name="Порядок в списке"),
        ),
    ]
