# Generated by Django 4.2.7 on 2023-12-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0022_brand_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="location_url",
            field=models.URLField(blank=True, null=True, verbose_name="Ссылка для локации (Google Maps, Yandex)"),
        ),
    ]
