# Generated by Django 4.2.7 on 2023-12-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0024_alter_brand_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="phone",
            field=models.IntegerField(default=991979899, help_text="Образец: 991979899", verbose_name="Телефон"),
        ),
    ]
