# Generated by Django 4.2.7 on 2023-12-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0025_alter_brand_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="arkon_file_android",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Укажите файл AR для других устройств, если в текущей странице нужно отображать AR",
                null=True,
                upload_to="",
                verbose_name="Файл AR Android",
            ),
        ),
        migrations.AddField(
            model_name="categories",
            name="arkon_file_android",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Укажите файл AR для других устройств, если в текущей странице нужно отображать AR",
                null=True,
                upload_to="",
                verbose_name="Файл AR Android",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="arkon_file_android",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Укажите файл AR для других устройств, если в текущей странице нужно отображать AR",
                null=True,
                upload_to="",
                verbose_name="Файл AR Android",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="arkon_file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Укажите файл AR для iPhone, если в текущей странице нужно отображать AR",
                null=True,
                upload_to="",
                verbose_name="Файл AR Iphone",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="arkon_file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Укажите файл AR для iPhone, если в текущей странице нужно отображать AR",
                null=True,
                upload_to="",
                verbose_name="Файл AR Iphone",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="arkon_file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="Укажите файл AR для iPhone, если в текущей странице нужно отображать AR",
                null=True,
                upload_to="",
                verbose_name="Файл AR Iphone",
            ),
        ),
    ]
