# Generated by Django 4.2.7 on 2023-12-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0026_brand_arkon_file_android_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="category_label",
            field=models.CharField(
                blank=True, default="Collections", max_length=100, null=True, verbose_name="Заголовок блока коллекций"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="information_label",
            field=models.CharField(
                blank=True,
                default="INFORMATION OF COMPANY",
                max_length=100,
                null=True,
                verbose_name="Заголовок блока информаций",
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="name_color",
            field=models.CharField(default="#FFFFFF", max_length=10, verbose_name="Цвет названия"),
        ),
        migrations.AddField(
            model_name="brand",
            name="product_label",
            field=models.CharField(
                blank=True, default="Products", max_length=100, null=True, verbose_name="Заголовок блока продуктов"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="slogan_color",
            field=models.CharField(default="#FFFFFF", max_length=10, verbose_name="Цвет слогана"),
        ),
        migrations.AddField(
            model_name="categories",
            name="name_color",
            field=models.CharField(default="#FFFFFF", max_length=10, verbose_name="Цвет названия"),
        ),
        migrations.AddField(
            model_name="categories",
            name="product_label",
            field=models.CharField(
                blank=True, default="Products", max_length=10, null=True, verbose_name="Заголовок блока продуктов"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_color",
            field=models.CharField(default="#FFFFFF", max_length=10, verbose_name="Цвет названия"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="email",
            field=models.EmailField(
                blank=True, default="info@arkon.uz", max_length=254, null=True, verbose_name="E-mail для связи"
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="email_support",
            field=models.CharField(
                blank=True, default="arkon.uz", max_length=100, null=True, verbose_name="Официальный сайт"
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Название"),
        ),
    ]
