# Generated by Django 4.2.7 on 2023-12-24 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stones", "0027_brand_category_label_brand_information_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="name_color",
        ),
    ]
