# Generated by Django 4.2.7 on 2023-12-24 20:04

from django.db import migrations, models
import django.db.models.deletion


def delete_characteristics(apps, schema_editor):
    Characteristic = apps.get_model("stones", "Characteristic")
    Characteristic.objects.all().delete()


def reverse_delete_characteristics(apps, schema_editor):
    # You can implement a reverse operation here if needed
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0003_table"),
        ("stones", "0028_remove_brand_name_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteristic",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="characteristics", to="categories.table"
            ),
        ),
        migrations.RunPython(delete_characteristics, reverse_code=reverse_delete_characteristics)
    ]
