# Generated by Django 4.2.7 on 2023-11-10 22:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("logo", models.ImageField(upload_to="mebels/brand", verbose_name="Логотип")),
                ("logo_light", models.ImageField(upload_to="stones/brand", verbose_name="Логотип для светлой версии")),
                ("image", models.ImageField(upload_to="mebels/brand", verbose_name="Изображение")),
            ],
            options={
                "verbose_name": "Бренд ",
                "verbose_name_plural": "Бренды ",
            },
        ),
    ]
