# Generated by Django 4.2.7 on 2023-11-29 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0001_initial"),
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="brands",
                to="categories.category",
                verbose_name="Категория",
            ),
        ),
    ]
