# Generated by Django 4.2.7 on 2023-11-30 01:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0003_alter_brand_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="logo_light",
        ),
    ]
