# Generated by Django 4.2.7 on 2023-12-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0004_remove_brand_logo_light"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="address",
            field=models.CharField(default="6A Лабзак, Ташкент", max_length=50, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="brand",
            name="email",
            field=models.EmailField(default="example@email.com", max_length=254, verbose_name="E-mail для связи"),
        ),
        migrations.AddField(
            model_name="brand",
            name="email_support",
            field=models.EmailField(default="example@email.com", max_length=254, verbose_name="E-mail для поддержки"),
        ),
        migrations.AddField(
            model_name="brand",
            name="location_url",
            field=models.URLField(
                default="https://maps.app.goo.gl/XZYYgEisV3hzBaWu5",
                verbose_name="Ссылка для локации (Google Maps, Yandex)",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="phone",
            field=models.CharField(default="+998712020020", max_length=50, verbose_name="Телефон"),
        ),
    ]
